#!/usr/bin/env python3
"""Feed teacher/student multi-turn sessions into the CoreCoder RL proxy.

RL methods:
- baseline: normal teacher-student interaction.
- opd: add an extra prompt generated by the current local/policy model.
- opsd: add an extra prompt generated by an external student/prompt model.
"""

from __future__ import annotations

import argparse
import json
import os
import time
import uuid
from pathlib import Path
from typing import Any

import httpx

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_SCENARIO_BANK = SCRIPT_DIR / "teacher_student_scenarios.jsonl"
DEFAULT_URL = "http://127.0.0.1:30000/v1/chat/completions"
DEFAULT_MODEL = "qwen3-4b"
DEFAULT_STUDENT_BASE_URL = "https://api.deepseek.com"
DEFAULT_STUDENT_MODEL = "deepseek-v4-flash"

FALLBACK_FOLLOW_UPS = [
    "I understand a little. Please explain the key step more slowly, like a patient teacher.",
    "Please check the previous answer again and point out the easiest place to make a mistake.",
    "Thanks. Please end with a short summary I can copy into my homework notes.",
]

STUDENT_SYSTEM_PROMPT = """You are role-playing a real student in a teacher-student tutoring dialogue.

Your job is to write the student's next message after reading the teacher's latest answer.
Behave like a plausible learner, not like an evaluator and not like another teacher.

Rules:
- Output only the student's next message. No JSON, no labels, no analysis.
- Do not solve the problem yourself unless a student would naturally show their attempt.
- React to the teacher's latest answer: ask for clarification, point out confusion, say what you understood, correct a mismatch, request a simpler explanation, or thank the teacher when resolved.
- Keep it short: 1-3 sentences.
- Match the scenario language when possible. If the original student speaks Chinese, reply in Chinese.
- If the teacher's answer is empty, off-topic, too terse, or confusing, ask the teacher to explain again.
- Make the feedback informative enough that a process reward model can judge whether the teacher's previous answer helped.
"""

EXTRA_PROMPT_SYSTEM_PROMPT = """You create an extra follow-up prompt for a student to send to a teacher model.

The goal is online prompt self-distillation for RL training: after seeing the teacher's latest answer and the student's natural reaction, write one additional student-side prompt that can make the next teacher response more useful, specific, and checkable.

Rules:
- Output only the extra prompt. No JSON, no labels, no analysis.
- Keep it short: 1-2 sentences.
- Match the conversation language when possible.
- Do not answer the homework/problem yourself.
- Ask for concrete correction, simpler reasoning, verification, examples, or formatting when helpful.
- The prompt should be useful as the next user message appended after the student's reaction.
"""


def load_scenarios(path: Path, limit: int) -> list[dict[str, Any]]:
    rows = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            rows.append(json.loads(line))
            if limit and len(rows) >= limit:
                break
    return rows


def post_turn(
    client: httpx.Client,
    url: str,
    api_key: str,
    model: str,
    session_id: str,
    messages: list[dict[str, Any]],
    done: bool,
    metadata: dict[str, Any] | None = None,
    turn_type: str = "main",
    max_tokens: int = 1024,
    temperature: float = 0.6,
) -> dict[str, Any]:
    headers = {"Authorization": f"Bearer {api_key}"} if api_key else {}
    payload = {
        "model": model,
        "session_id": session_id,
        "turn_type": turn_type,
        "session_done": done,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    if metadata:
        payload.update({k: v for k, v in metadata.items() if v not in (None, "")})
    resp = client.post(url, headers=headers, json=payload, timeout=None)
    resp.raise_for_status()
    return resp.json()


def assistant_message(output: dict[str, Any]) -> dict[str, Any]:
    choice = (output.get("choices") or [{}])[0]
    msg = dict(choice.get("message") or {})
    msg.setdefault("role", "assistant")
    if msg.get("content") is None:
        msg["content"] = ""
    return msg


def _history_for_student(scenario: dict[str, Any], messages: list[dict[str, Any]]) -> str:
    lines = [
        f"Scenario id: {scenario.get('scenario_id', '')}",
        f"Scenario domain: {scenario.get('domain', '')}",
        "Conversation so far:",
    ]
    for msg in messages[-8:]:
        role = msg.get("role", "")
        if role == "user":
            name = "Student"
        elif role == "assistant":
            name = "Teacher"
        else:
            name = role.title() or "Message"
        content = str(msg.get("content") or "").strip()
        if content:
            lines.append(f"{name}: {content}")
    lines.append("Write the student's next message now.")
    return "\n\n".join(lines)


def _history_for_extra_prompt(scenario: dict[str, Any], messages: list[dict[str, Any]], student_followup: str) -> str:
    lines = [
        f"Scenario id: {scenario.get('scenario_id', '')}",
        f"Scenario domain: {scenario.get('domain', '')}",
        "Conversation so far:",
    ]
    for msg in messages[-8:]:
        role = msg.get("role", "")
        name = "Student" if role == "user" else "Teacher" if role == "assistant" else (role.title() or "Message")
        content = str(msg.get("content") or "").strip()
        if content:
            lines.append(f"{name}: {content}")
    lines.append(f"Natural student reaction already drafted: {student_followup}")
    lines.append("Write the extra prompt that should be appended after that reaction.")
    return "\n\n".join(lines)


def _chat_external(client: httpx.Client, args: argparse.Namespace, system_prompt: str, user_prompt: str) -> str:
    if not args.student_api_key:
        raise RuntimeError("DeepSeek-backed mode requires --student-api-key or DEEPSEEK_API_KEY")
    payload = {
        "model": args.student_model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": args.student_temperature,
        "max_tokens": args.student_max_tokens,
        "stream": False,
    }
    url = args.student_base_url.rstrip("/") + "/v1/chat/completions"
    headers = {"Authorization": f"Bearer {args.student_api_key}", "Content-Type": "application/json"}
    resp = client.post(url, headers=headers, json=payload, timeout=args.student_timeout)
    resp.raise_for_status()
    data = resp.json()
    return (((data.get("choices") or [{}])[0].get("message") or {}).get("content") or "").strip()


def generate_student_followup(client: httpx.Client, args: argparse.Namespace, scenario: dict[str, Any], messages: list[dict[str, Any]], turn: int) -> str:
    if args.student_mode == "fixed":
        return FALLBACK_FOLLOW_UPS[turn % len(FALLBACK_FOLLOW_UPS)]
    text = _chat_external(client, args, STUDENT_SYSTEM_PROMPT, _history_for_student(scenario, messages))
    if not text:
        return "I am still not sure I understood. Could you explain it again in a simpler way?"
    return text


def generate_extra_prompt(
    client: httpx.Client,
    args: argparse.Namespace,
    scenario: dict[str, Any],
    messages: list[dict[str, Any]],
    student_followup: str,
    session_id: str,
    metadata: dict[str, Any] | None,
) -> tuple[str, str, str]:
    if args.rl_method == "baseline":
        return "", "none", "none"

    user_prompt = _history_for_extra_prompt(scenario, messages, student_followup)
    if args.rl_method == "opsd":
        text = _chat_external(client, args, EXTRA_PROMPT_SYSTEM_PROMPT, user_prompt)
        return text.strip(), "external", args.student_model

    # OPD: use the current local/policy model via the CoreCoder proxy as a side request.
    side_messages = [
        {"role": "system", "content": EXTRA_PROMPT_SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt},
    ]
    output = post_turn(
        client,
        args.url,
        args.api_key,
        args.model,
        f"{session_id}-opd-side-{uuid.uuid4().hex[:6]}",
        side_messages,
        done=False,
        metadata=metadata,
        turn_type="side",
        max_tokens=args.extra_prompt_max_tokens,
        temperature=args.extra_prompt_temperature,
    )
    text = assistant_message(output).get("content", "").strip()
    return text, "policy", args.model


def compose_followup(student_followup: str, extra_prompt: str) -> str:
    student_followup = student_followup.strip()
    extra_prompt = extra_prompt.strip()
    if not extra_prompt:
        return student_followup
    if any("\u4e00" <= ch <= "\u9fff" for ch in student_followup + extra_prompt):
        return f"{student_followup}\n\n?????{extra_prompt}"
    return f"{student_followup}\n\nExtra prompt: {extra_prompt}"


def run_session(client: httpx.Client, args: argparse.Namespace, scenario: dict[str, Any]) -> dict[str, Any]:
    session_id = f"corecoder-{args.rl_method}-{scenario.get('scenario_id', 'scenario')}-{uuid.uuid4().hex[:8]}"
    target_turns = max(1, int(scenario.get("target_turns", 2)))
    messages = [{"role": "user", "content": scenario["opening_user_message"]}]
    transcript = []
    metadata = None
    if args.send_metadata:
        metadata = {
            "scenario_id": scenario.get("scenario_id"),
            "student_mode": args.student_mode,
            "student_model": args.student_model if args.student_mode == "deepseek" else "fixed",
            "feeder_id": args.feeder_id,
            "rl_method": args.rl_method,
        }
    for turn in range(target_turns):
        done = turn == target_turns - 1
        output = post_turn(client, args.url, args.api_key, args.model, session_id, messages, done, metadata)
        msg = assistant_message(output)
        transcript.append({"user": messages[-1]["content"], "assistant": msg.get("content", "")})
        messages.append(msg)
        if not done:
            follow = generate_student_followup(client, args, scenario, messages, turn)
            extra_prompt, prompt_source, extra_prompt_model = generate_extra_prompt(
                client, args, scenario, messages, follow, session_id, metadata
            )
            if metadata is not None:
                metadata.update({
                    "prompt_source": prompt_source,
                    "extra_prompt_model": extra_prompt_model,
                })
            messages.append({"role": "user", "content": compose_followup(follow, extra_prompt)})
            transcript[-1]["student_followup"] = follow
            transcript[-1]["extra_prompt"] = extra_prompt
            transcript[-1]["prompt_source"] = prompt_source
            transcript[-1]["extra_prompt_model"] = extra_prompt_model
            time.sleep(args.turn_delay)
    return {
        "session_id": session_id,
        "scenario_id": scenario.get("scenario_id"),
        "rl_method": args.rl_method,
        "student_mode": args.student_mode,
        "student_model": args.student_model if args.student_mode == "deepseek" else "fixed",
        "turns": len(transcript),
        "transcript": transcript,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scenario-bank", type=Path, default=Path(os.getenv("CORECODER_SCENARIO_BANK", DEFAULT_SCENARIO_BANK)))
    parser.add_argument("--url", default=os.getenv("CORECODER_RL_URL", DEFAULT_URL))
    parser.add_argument("--api-key", default=os.getenv("CORECODER_RL_API_KEY", os.getenv("SGLANG_API_KEY", "change-me")))
    parser.add_argument("--model", default=os.getenv("CORECODER_RL_MODEL", DEFAULT_MODEL))
    parser.add_argument("--limit", type=int, default=int(os.getenv("CORECODER_FEEDER_LIMIT", "2")))
    parser.add_argument("--turn-delay", type=float, default=float(os.getenv("CORECODER_FEEDER_TURN_DELAY", "0.5")))
    parser.add_argument("--output", type=Path, default=Path(os.getenv("CORECODER_FEEDER_OUTPUT", "/root/autodl-tmp/corecoder_rl/logs/corecoder_teacher_student_feeder.jsonl")))
    parser.add_argument("--student-mode", choices=["deepseek", "fixed"], default=os.getenv("CORECODER_STUDENT_MODE", "deepseek"))
    parser.add_argument("--rl-method", choices=["baseline", "opd", "opsd"], default=os.getenv("CORECODER_RL_METHOD", "baseline"))
    parser.add_argument("--student-base-url", default=os.getenv("DEEPSEEK_BASE_URL", DEFAULT_STUDENT_BASE_URL))
    parser.add_argument("--student-api-key", default=os.getenv("DEEPSEEK_API_KEY", ""))
    parser.add_argument("--student-model", default=os.getenv("DEEPSEEK_MODEL", DEFAULT_STUDENT_MODEL))
    parser.add_argument("--student-temperature", type=float, default=float(os.getenv("DEEPSEEK_STUDENT_TEMPERATURE", "0.8")))
    parser.add_argument("--student-max-tokens", type=int, default=int(os.getenv("DEEPSEEK_STUDENT_MAX_TOKENS", "512")))
    parser.add_argument("--student-timeout", type=float, default=float(os.getenv("DEEPSEEK_STUDENT_TIMEOUT", "60")))
    parser.add_argument("--extra-prompt-temperature", type=float, default=float(os.getenv("CORECODER_EXTRA_PROMPT_TEMPERATURE", "0.7")))
    parser.add_argument("--extra-prompt-max-tokens", type=int, default=int(os.getenv("CORECODER_EXTRA_PROMPT_MAX_TOKENS", "256")))
    parser.add_argument("--feeder-id", default=os.getenv("CORECODER_FEEDER_ID", "teacher_student_feeder"))
    parser.add_argument("--send-metadata", action=argparse.BooleanOptionalAction, default=os.getenv("CORECODER_SEND_METADATA", "1").lower() not in {"0", "false", "no", "off"})
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    scenarios = load_scenarios(args.scenario_bank, args.limit)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if args.dry_run:
        print(json.dumps({
            "url": args.url,
            "model": args.model,
            "rl_method": args.rl_method,
            "student_mode": args.student_mode,
            "student_model": args.student_model if args.student_mode == "deepseek" else "fixed",
            "send_metadata": args.send_metadata,
            "scenarios": [s.get("scenario_id") for s in scenarios],
        }, ensure_ascii=False))
        return 0
    with httpx.Client() as client, args.output.open("a", encoding="utf-8") as out:
        for scenario in scenarios:
            row = run_session(client, args, scenario)
            out.write(json.dumps(row, ensure_ascii=False) + "\n")
            out.flush()
            print(json.dumps({
                "fed": row["session_id"],
                "turns": row["turns"],
                "rl_method": row["rl_method"],
                "student_model": row["student_model"],
            }, ensure_ascii=False), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
